/*
-- Query: 
-- Date: 2016-04-25 14:49
*/
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2160','AGUILA LIG R 330 CC X 30','CANASTA AGUILA LIGHT',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2182','PONY MALTA R 330 CC X 30','CANASTA PONY MALTA',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2183','PONY MALTA R 225 CC X 38','CANASTA PONY MALTA',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2298','REDDS COLD R 330 CC X 30','CANASTA REDDS COLD',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2511','COLA&POLA R 330 CC X 30','CANASTA COLA&POLA',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2512','POKER R 330 CC X 30','CANASTA POKER',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2634','PILSEN RNN 330 CC X 30','CANASTA PILSEN',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3128','AGUILA RN 330 CC X 30','CANASTA AGUILA 330 CC',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3130','AGUILA RN 225 CC X 38','CANASTA AGUILA 225 CC',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3198','COSTEÑA RN 350 CC X 30','CANASTA COSTEÑA CC',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3130','COSTEÑITA RN 225 CC X 30','CANASTA COSTEÑITA 225 CC',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2634','PILSEN R 750 CC X 38','CANASTA PILSEN 750 CC',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3664','AGUILA LIG R 750 CC X 16','CANASTA AGUILA LIGHT 750 CC',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3751','CLUB COL R 330 CC X 30','CANASTA CLUB COLOMBIA',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3759','CLUB COL RJ 330 CC X 30 N','CANASTA CLUB COLOMBIA ROJA',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3760','CLUB COL NG 330 CC X 30 N','CANASTA CLUB COLOMBIA NEGRA',1);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('1262','PERONI TW 330 CC X 24','CANASTA PERONI',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('1436','CLUB COL TW 330 CC X 24','CANASTA CLUB COLOMBIA',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2154','AGUILA TW 330 CC X 24','CANASTA AGUILA TW',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2157','AGUILA LIG TW 330 CC X 24','CANASTA AGUILA LIGHT TW',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2302','REDDS COLD 330 CC X 24','CANASTA REDDS COLD TW',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2514','POKER TW 330 CC X 24','CANASTA POKER TW',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2637','PILSEN TW 330 CC X 24','CANASTA PILSEN TW',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3205','MILLER GD TW 350 CC X 24','CANASTA MILLER GD TW',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3753','CLUB COL TW 330 CC X 24 N','CANASTA CLUB COLOMBIA TW',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3756','CLUB COL RJ TW 330 CC X 24 N','CANASTA CLUB COLOMBIA ROJA TW',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3758','CLUB COL NG TW 330 CC X 24 N','CANASTA CLUB COLOMBIA NEGRA TW',2);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('1416','COSTEÑA LTA 330 CC X 24','COSTEÑA LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('1421','COLA&POLA LTA 330 CC X 24','COLA&POLA LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('1431','POKER LTA 330 CC X 24','POKER LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2170','AGUILA LIGHT LTA 330 CC X 24','AGUILA LIGHT LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2171','AGUILA LIGHT LTA 330 CC X 6','AGUILA LIGHT LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2173','AGUILA LTA 330 CC X 24','AGUILA LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2174','AGUILA LTA 330 CC X 6','AGUILA LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2206','PONY MALTA LTA 330 CC X 24','PONY MALTA LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2640','PILSEN LTA 330 CC X 24','PILSEN LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2641','PILSEN LTA 330 CC X 6','PILSEN LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3203','REDDS COLD LTA 269 CC X 24','REDDS COLD LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3228','REDDS COLD LTA 269 CC X 6','REDDS COLD LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3656','AGUILA LTA 269 CC X 24','AGUILA LATA 269 CC',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('5250','CLUB COL LTA 330 CC X 24 N','CLUB COLOMBIA LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('5252','CLUB COL LTA 330 CC X 6 N','CLUB COLOMBIA LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('5250','CLUB COL RJ LTA 330 CC X 24 N','CLUB COLOMBIA ROJA LATA',3);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('26','AGUILA BRR 50L X 1','AGUILA BARRIL',4);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('31','CLUB COL BRR 30L X 1','CLUB COLOMBIA BARRIL',4);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('4044','CLUB COL RJ BRR 30L X 1','CLUB COLOMBIA ROJA BARRIL',4);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('5626','CLUB COL BRR 30L X 1 OKF','CLUB COLOMBIA BARRIL',4);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2222','PONY MALTA PET 330 CC X 24','PONY MALTA PET',5);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2223','PONY MALTA PET 330 CC X 6','PONY MALTA PET',5);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2224','PONY MALTA PET 1.5 L X 6','PONY MALTA PET',5);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2759','PONY MALTA PET 200 X CC X 6','PONY MALTA PET',5);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('2882','COLA&POLA PET 1.5 L X 6','COLA&POLA PET',5);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3810','PONY MALTA PET 200 X CC X 30','PONY MALTA PET',5);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('4467','PONY MALTA PET 1 L X 12','PONY MALTA PET',5);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('4468','PONY MALTA PET 1 L X 15','PONY MALTA PET',5);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3500163','ESTIBA CERV MADERA 330 CC 1280 X 10808 X 120','PONY MALTA PET',7);
INSERT INTO `producto` (`cod_producto`,`nom_producto`,`des_producto`,`tipo_producto`) VALUES ('3500163','CILINDRO CO2 20 KG','CILINDRO CO2 20 Kg',6);